version: '2'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .mysql:/var/lib/mysql
    ports: 
      - 3306:3306
 
